using Microsoft.Extensions.AI;

namespace AgentBlazor.Core.Runtime.Conversation;

/// <summary>
/// Token usage reported by the model provider for a single conversation turn.
/// <para>
/// This is the persistable projection of <see cref="UsageDetails"/>: a plain,
/// immutable value type with no provider-specific or mutable aggregation state, so
/// conversation stores can round-trip it without depending on the AI abstractions.
/// All counts are nullable because providers report usage inconsistently — a turn
/// that was short-circuited, served from cache, or produced by a provider that omits
/// usage will have no counts at all.
/// </para>
/// <para>
/// Cost is deliberately <b>not</b> part of this type. Pricing is a consumer policy
/// (rates change per model and per contract), so consumers derive cost from these
/// counts and persist it alongside their own rate snapshot.
/// </para>
/// </summary>
public sealed record ConversationTurnUsage
{
    /// <summary>Tokens sent to the model (prompt tokens).</summary>
    public long? InputTokens { get; init; }

    /// <summary>Tokens generated by the model (completion tokens).</summary>
    public long? OutputTokens { get; init; }

    /// <summary>Total tokens reported by the provider, when it reports one.</summary>
    public long? TotalTokens { get; init; }

    /// <summary>
    /// Input tokens served from the provider's prompt cache, when reported.
    /// Typically billed at a discounted rate.
    /// </summary>
    public long? CachedInputTokens { get; init; }

    /// <summary>
    /// Whether any token count was reported. A usage record with no counts carries
    /// no information and is normalized to <see langword="null"/> by
    /// <see cref="FromUsageDetails"/>.
    /// </summary>
    public bool HasAnyCounts =>
        InputTokens is not null ||
        OutputTokens is not null ||
        TotalTokens is not null ||
        CachedInputTokens is not null;

    /// <summary>
    /// Projects provider usage onto a persistable record.
    /// </summary>
    /// <param name="usage">The provider usage, or <see langword="null"/>.</param>
    /// <returns>
    /// The projected usage, or <see langword="null"/> when <paramref name="usage"/>
    /// is <see langword="null"/> or reported no counts at all.
    /// </returns>
    public static ConversationTurnUsage? FromUsageDetails(UsageDetails? usage)
    {
        if (usage is null)
        {
            return null;
        }

        var projected = new ConversationTurnUsage
        {
            InputTokens = usage.InputTokenCount,
            OutputTokens = usage.OutputTokenCount,
            TotalTokens = usage.TotalTokenCount,
            CachedInputTokens = usage.CachedInputTokenCount
        };

        return projected.HasAnyCounts ? projected : null;
    }
}