using System.Text.Json;
using AgentBlazor.Demo.Data;
using AgentBlazor.Execution;
using Microsoft.EntityFrameworkCore;

namespace AgentBlazor.Demo.Services;

/// <summary>
/// Consolidated per-session rollups over <see cref="DemoDbContext"/> for every
/// <c>ConversationTurn</c>-derived aspect the session browser reads: token/cost usage
/// columns and the persisted <c>ExecutionPlanJson</c> blobs.
/// <para>
/// The two former query services (<c>DemoConversationUsageQuery</c> +
/// <c>DemoConversationPlanQuery</c>) each issued their own session lookup and turns
/// query per session. This single query resolves all requested sessions in one query
/// and loads all their turns in one query, then aggregates usage + plan in C# — so a
/// full browser page costs two roundtrips regardless of session count.
/// </para>
/// </summary>
public interface IDemoConversationTurnQuery
{
    /// <summary>
    /// Returns the combined usage + execution-plan detail for one conversation session.
    /// </summary>
    /// <param name="sessionKey">The full store session key (includes the <c>::agent::</c> suffix when isolation is on).</param>
    /// <returns>
    /// The detail, or <see langword="null"/> when the session does not exist.
    /// Individual aspects (<see cref="SessionConversationDetail.Usage"/> /
    /// <see cref="SessionConversationDetail.Plan"/>) are null when the session's turns
    /// carry no data for that aspect (e.g. rows persisted before the columns existed).
    /// </returns>
    Task<SessionConversationDetail?> GetSessionDetailAsync(
        string sessionKey,
        CancellationToken ct = default);

    /// <summary>
    /// Returns the combined usage + execution-plan detail for many conversation sessions
    /// in a single batch: one session lookup query plus one turns query total.
    /// </summary>
    /// <param name="sessionKeys">The full store session keys to load.</param>
    /// <returns>
    /// One detail per existing session (missing keys are omitted). Aspects are null when
    /// the session's turns carry no data for that aspect.
    /// </returns>
    Task<IReadOnlyList<SessionConversationDetail>> GetSessionDetailsAsync(
        IReadOnlyCollection<string> sessionKeys,
        CancellationToken ct = default);
}

/// <summary>
/// Aggregated token usage and estimated cost for one conversation session.
/// </summary>
/// <param name="PromptTokens">Tokens sent to the model (input).</param>
/// <param name="CompletionTokens">Tokens generated by the model (output).</param>
/// <param name="CachedInputTokens">
/// Input tokens served from the provider's prompt cache. A subset of
/// <paramref name="PromptTokens"/>, not an additional count.
/// </param>
/// <param name="TotalTokens">Total tokens reported by the provider.</param>
/// <param name="EstimatedCost">Estimated cost in <paramref name="EstimatedCostCurrency"/>.</param>
/// <param name="EstimatedCostCurrency">Currency of <paramref name="EstimatedCost"/> (always <c>USD</c> in the Demo).</param>
public sealed record SessionUsageTotals(
    long PromptTokens,
    long CompletionTokens,
    long CachedInputTokens,
    long TotalTokens,
    decimal EstimatedCost,
    string? EstimatedCostCurrency);

/// <summary>
/// Aggregated execution-plan statistics for one conversation session.
/// </summary>
/// <param name="TurnsWithPlan">Number of turns whose execution plan was persisted.</param>
/// <param name="TotalSteps">Total execution steps across the session's persisted plans.</param>
/// <param name="ApprovalRequiredSteps">Execution steps that require (or required) approval.</param>
public sealed record SessionExecutionPlanSummary(
    int TurnsWithPlan,
    int TotalSteps,
    int ApprovalRequiredSteps);

/// <summary>
/// Combined per-session detail returned by <see cref="IDemoConversationTurnQuery"/>.
/// </summary>
/// <param name="SessionKey">The full store session key.</param>
/// <param name="Usage">Token/cost totals, or <see langword="null"/> when no turn recorded usage.</param>
/// <param name="Plan">Execution-plan statistics, or <see langword="null"/> when no turn persisted a plan.</param>
public sealed record SessionConversationDetail(
    string SessionKey,
    SessionUsageTotals? Usage,
    SessionExecutionPlanSummary? Plan);

/// <summary>
/// SQL Server-backed <see cref="IDemoConversationTurnQuery"/> over the conversation database.
/// </summary>
internal sealed class DemoConversationTurnQuery(IDbContextFactory<DemoDbContext> dbFactory)
    : IDemoConversationTurnQuery
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    public async Task<SessionConversationDetail?> GetSessionDetailAsync(
        string sessionKey,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionKey);

        var details = await GetSessionDetailsAsync([sessionKey], ct);
        return details.FirstOrDefault();
    }

    public async Task<IReadOnlyList<SessionConversationDetail>> GetSessionDetailsAsync(
        IReadOnlyCollection<string> sessionKeys,
        CancellationToken ct = default)
    {
        if (sessionKeys.Count == 0)
        {
            return [];
        }

        var keys = sessionKeys.ToList();

        await using var db = await dbFactory.CreateDbContextAsync(ct);

        // ONE query: resolve every requested session at once.
        var sessions = await db.Sessions
            .AsNoTracking()
            .Where(s => keys.Contains(s.SessionId))
            .Select(s => new SessionRef(s.Id, s.SessionId))
            .ToListAsync(ct);

        if (sessions.Count == 0)
        {
            return [];
        }

        var sessionIds = sessions.Select(static s => s.Id).ToList();

        // ONE query: load every turn-derived column for all requested sessions.
        var turns = await db.Turns
            .AsNoTracking()
            .Where(t => sessionIds.Contains(t.SessionId))
            .Select(t => new TurnProjection(
                t.SessionId,
                t.PromptTokens,
                t.CompletionTokens,
                t.CachedInputTokens,
                t.TotalTokens,
                t.EstimatedCost,
                t.EstimatedCostCurrency,
                t.ExecutionPlanJson))
            .ToListAsync(ct);

        var turnsBySession = turns.ToLookup(static t => t.SessionId);

        var results = new List<SessionConversationDetail>(sessions.Count);
        foreach (var session in sessions)
        {
            var sessionTurns = turnsBySession[session.Id];
            results.Add(new SessionConversationDetail(
                session.SessionId,
                BuildUsageTotals(sessionTurns),
                BuildPlanSummary(sessionTurns)));
        }

        return results;
    }

    private static SessionUsageTotals? BuildUsageTotals(IEnumerable<TurnProjection> turns)
    {
        var list = turns.ToList();

        // Sessions persisted before the usage columns existed have no usage at all —
        // report null so the UI can distinguish "no data" from "zero usage".
        if (list.All(static t =>
                t.PromptTokens is null &&
                t.CompletionTokens is null &&
                t.CachedInputTokens is null &&
                t.TotalTokens is null &&
                t.EstimatedCost is null))
        {
            return null;
        }

        return new SessionUsageTotals(
            PromptTokens: list.Sum(static t => t.PromptTokens ?? 0),
            CompletionTokens: list.Sum(static t => t.CompletionTokens ?? 0),
            CachedInputTokens: list.Sum(static t => t.CachedInputTokens ?? 0),
            TotalTokens: list.Sum(static t => t.TotalTokens ?? 0),
            EstimatedCost: list.Sum(static t => t.EstimatedCost ?? 0m),
            EstimatedCostCurrency: list
                .FirstOrDefault(static t => t.EstimatedCostCurrency is not null)
                ?.EstimatedCostCurrency);
    }

    private static SessionExecutionPlanSummary? BuildPlanSummary(IEnumerable<TurnProjection> turns)
    {
        var turnsWithPlan = 0;
        var totalSteps = 0;
        var approvalRequiredSteps = 0;

        foreach (var turn in turns)
        {
            if (string.IsNullOrWhiteSpace(turn.ExecutionPlanJson))
            {
                continue;
            }

            AgentExecutionPlan? plan = null;
            try
            {
                plan = JsonSerializer.Deserialize<AgentExecutionPlan>(turn.ExecutionPlanJson, JsonOptions);
            }
            catch (JsonException)
            {
                // A corrupt row must not break the browser — skip it.
            }

            if (plan?.Steps.Count > 0)
            {
                turnsWithPlan++;
                totalSteps += plan.Steps.Count;
                approvalRequiredSteps += plan.Steps.Count(static step => step.RequiresApproval);
            }
        }

        if (turnsWithPlan == 0)
        {
            return null;
        }

        return new SessionExecutionPlanSummary(turnsWithPlan, totalSteps, approvalRequiredSteps);
    }

    private sealed record SessionRef(Guid Id, string SessionId);

    private sealed record TurnProjection(
        Guid SessionId,
        long? PromptTokens,
        long? CompletionTokens,
        long? CachedInputTokens,
        long? TotalTokens,
        decimal? EstimatedCost,
        string? EstimatedCostCurrency,
        string? ExecutionPlanJson);
}

/// <summary>
/// No-op <see cref="IDemoConversationTurnQuery"/> used when the conversation store is not
/// the EF Core one (JsonFile / InMemory) — mirrors the library's Null-store convention so
/// consumers never need to branch on the store backend.
/// </summary>
internal sealed class NullDemoConversationTurnQuery : IDemoConversationTurnQuery
{
    public Task<SessionConversationDetail?> GetSessionDetailAsync(
        string sessionKey,
        CancellationToken ct = default)
        => Task.FromResult<SessionConversationDetail?>(null);

    public Task<IReadOnlyList<SessionConversationDetail>> GetSessionDetailsAsync(
        IReadOnlyCollection<string> sessionKeys,
        CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<SessionConversationDetail>>([]);
}