using AgentBlazor.Demo.Data;
using Microsoft.EntityFrameworkCore;

namespace AgentBlazor.Demo.Services;

/// <summary>
/// Per-session token/cost rollups over <see cref="DemoDbContext"/>.
/// <para>
/// Cost is a Demo-side policy (see <see cref="DemoUsageCostCalculator"/>), so it is not part
/// of the library <c>ConversationTurn</c> — this query is how the session browser reads the
/// persisted usage columns back out of the conversation database.
/// </para>
/// </summary>
public interface IDemoConversationUsageQuery
{
    /// <summary>
    /// Returns the token/cost totals for one conversation session.
    /// </summary>
    /// <param name="sessionKey">The full store session key (includes the <c>::agent::</c> suffix when isolation is on).</param>
    /// <returns>
    /// The totals, or <see langword="null"/> when the session does not exist or none of its
    /// turns carry usage data (e.g. rows persisted before the usage columns existed).
    /// </returns>
    Task<SessionUsageTotals?> GetSessionTotalsAsync(string sessionKey, CancellationToken ct = default);
}

/// <summary>
/// Aggregated token usage and estimated cost for one conversation session.
/// </summary>
/// <param name="PromptTokens">Tokens sent to the model (input).</param>
/// <param name="CompletionTokens">Tokens generated by the model (output).</param>
/// <param name="CachedInputTokens">
/// Input tokens served from the provider's prompt cache. A subset of
/// <paramref name="PromptTokens"/>, not an additional count.
/// </param>
/// <param name="TotalTokens">Total tokens reported by the provider.</param>
/// <param name="EstimatedCost">Estimated cost in <paramref name="EstimatedCostCurrency"/>.</param>
/// <param name="EstimatedCostCurrency">Currency of <paramref name="EstimatedCost"/> (always <c>USD</c> in the Demo).</param>
public sealed record SessionUsageTotals(
    long PromptTokens,
    long CompletionTokens,
    long CachedInputTokens,
    long TotalTokens,
    decimal EstimatedCost,
    string? EstimatedCostCurrency);

/// <summary>
/// SQLite-backed <see cref="IDemoConversationUsageQuery"/> over the conversation database.
/// </summary>
internal sealed class DemoConversationUsageQuery(IDbContextFactory<DemoDbContext> dbFactory)
    : IDemoConversationUsageQuery
{
    public async Task<SessionUsageTotals?> GetSessionTotalsAsync(
        string sessionKey,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionKey);

        await using var db = await dbFactory.CreateDbContextAsync(ct);

        var session = await db.Sessions
            .AsNoTracking()
            .FirstOrDefaultAsync(s => s.SessionId == sessionKey, ct);
        if (session is null)
        {
            return null;
        }

        var turns = await db.Turns
            .AsNoTracking()
            .Where(t => t.SessionId == session.Id)
            .Select(t => new
            {
                t.PromptTokens,
                t.CompletionTokens,
                t.CachedInputTokens,
                t.TotalTokens,
                t.EstimatedCost,
                t.EstimatedCostCurrency
            })
            .ToListAsync(ct);

        // Sessions persisted before the usage columns existed have no usage at all —
        // report null so the UI can distinguish "no data" from "zero usage".
        if (turns.All(static t =>
                t.PromptTokens is null &&
                t.CompletionTokens is null &&
                t.CachedInputTokens is null &&
                t.TotalTokens is null &&
                t.EstimatedCost is null))
        {
            return null;
        }

        return new SessionUsageTotals(
            PromptTokens: turns.Sum(static t => t.PromptTokens ?? 0),
            CompletionTokens: turns.Sum(static t => t.CompletionTokens ?? 0),
            CachedInputTokens: turns.Sum(static t => t.CachedInputTokens ?? 0),
            TotalTokens: turns.Sum(static t => t.TotalTokens ?? 0),
            EstimatedCost: turns.Sum(static t => t.EstimatedCost ?? 0m),
            EstimatedCostCurrency: turns
                .FirstOrDefault(static t => t.EstimatedCostCurrency is not null)
                ?.EstimatedCostCurrency);
    }
}

/// <summary>
/// No-op <see cref="IDemoConversationUsageQuery"/> used when the conversation store is not
/// the EF Core one (JsonFile / InMemory) — mirrors the library's Null-store convention so
/// consumers never need to branch on the store backend.
/// </summary>
internal sealed class NullDemoConversationUsageQuery : IDemoConversationUsageQuery
{
    public Task<SessionUsageTotals?> GetSessionTotalsAsync(
        string sessionKey,
        CancellationToken ct = default)
        => Task.FromResult<SessionUsageTotals?>(null);
}