// <auto-generated />
using System;
using AgentBlazor.Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentBlazor.Demo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AgentBlazor.Core.Persistence.AgentDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowedComponentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowedDataSchemasJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledToolsJson")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AgentBlazor.Core.Persistence.ConversationSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AgentBlazor.Core.Persistence.ConversationTurnEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("AgentResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CachedInputTokenCostPerMillion")
                        .HasColumnType("REAL");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EstimatedCost")
                        .HasColumnType("REAL");

                    b.Property<string>("EstimatedCostCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionPlanJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionResultsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedUiJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InputTokenCostPerMillion")
                        .HasColumnType("REAL");

                    b.Property<double?>("OutputTokenCostPerMillion")
                        .HasColumnType("REAL");

                    b.Property<string>("PlannedActionsJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AgentBlazor.Demo.Data.DemoAgentDefinitionEntity", b =>
                {
                    b.HasBaseType("AgentBlazor.Core.Persistence.AgentDefinitionEntity");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("demo_agent_definitions", (string)null);
                });

            modelBuilder.Entity("AgentBlazor.Demo.Data.DemoConversationSessionEntity", b =>
                {
                    b.HasBaseType("AgentBlazor.Core.Persistence.ConversationSessionEntity");

                    b.HasIndex("LastActivityAtUtc");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("demo_conversation_sessions", (string)null);
                });

            modelBuilder.Entity("AgentBlazor.Demo.Data.DemoConversationTurnEntity", b =>
                {
                    b.HasBaseType("AgentBlazor.Core.Persistence.ConversationTurnEntity");

                    b.HasIndex("SessionId", "TurnId")
                        .IsUnique();

                    b.ToTable("demo_conversation_turns", (string)null);
                });

            modelBuilder.Entity("AgentBlazor.Core.Persistence.ConversationTurnEntity", b =>
                {
                    b.HasOne("AgentBlazor.Core.Persistence.ConversationSessionEntity", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentBlazor.Core.Persistence.ConversationSessionEntity", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
